### ISSUE TITLE
website: Improve the website of mind expanding books

### ISSUE THREAD

**Issue by hackerkid** [hackerkid/Mind-Expanding-Books#178]
I have built a bare minimum website for mind expanding books using Gatsby. Its acessible at http://books.vishnuks.com. 

The source code of the website lives in `app` directory and the README in app directory has documentation on how to start a development environment.

If you are interested in improving the website feel free to contribute. Some issues that are on top of the mind are

- [x] Show the year book is published.

- [x] Show rating as stars for each book

- [x]  Add a navbar or menu bar that allows users to filter books category wise #182 

- [ ] Add a sort funtionality. ie users should be able to sort books on basis of rating, year published, alpabetical order of title etc #183

- [x] Add an infinite scroll instead of loading all the books. #184

- [x] There should be a seperate page for each category. ie /Startups-Business urls should display books from that category. #185

- [x] Make the UI of the cards better. #186

- [ ] Add functionality to mark book as "to read" using local storage. #187

If you are interested in working on one of these issues feel free to comment on the issue page to assign you the issue.

If you have any other idea for improving the website feel free to create a new issue and start working on it.

**Comment by SurajKhayamali** [comment]
I am working on infinite scroll.
Possibly, Assign me.

**Comment by hackerkid** [comment]
@SurajKhayamali Awesome. Go ahead and work on it.

**Comment by hackerkid** [comment]
@SurajKhayamali I created https://github.com/hackerkid/Mind-Expanding-Books/issues/184. if you can comment there asking to assign you the issue I can assign it for you. GitHub don't allow to assign users without them commenting on the issue.

**Comment by hackerkid** [comment]
Most of the issues here are fixed. For the remaining ones, there are existing issues opened.
